# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cccccf197d2c5b7f64378e4ee5c12e3bcd2147d66e408c4972acb60520c43a55405a5791925f35cbe596f1fca3dad97aad778fca901cec046428ba53b90c8df0

test:
  secret_key_base: d325d9bb602223edc096683713a229a044e49bafe8e167c69c3df6b51f63a5a661284bc6de8d601cf83bcece4fe0db31312df343d1288584e4ab6a2647502b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
